server {
  listen 80;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;
  types { application/wasm wasm; }
  add_header Cache-Control "no-store";
  location /build/ { alias /build/; }
  location / { try_files $uri $uri/ =404; }
}
